# Generated by Django 3.0.3 on 2020-06-19 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Predictor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=10)),
                ('to_predict', models.CharField(choices=[('cases', 'Active Cases'), ('deaths', 'Deaths'), ('cured', 'Cured')], default='cases', max_length=20)),
            ],
        ),
    ]
