# Generated by Django 2.2.5 on 2020-06-19 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predictor',
            name='to_predict',
            field=models.CharField(choices=[('cases', 'Active Cases'), ('deaths', 'Deaths')], default='cases', max_length=20),
        ),
    ]
