# Generated by Django 2.2.5 on 2020-06-19 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0002_auto_20200619_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predictor',
            name='to_predict',
            field=models.CharField(choices=[('cases', 'Active Cases'), ('deaths', 'Deaths'), ('cured', 'Cured')], default='cases', max_length=20),
        ),
    ]
